///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace StandaloneRetechPayWirthCash
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
            
        for (int i = 1; i <=10; i++)
        {
            	

            
             Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShellView.ButtonText' at 54;0.", repo.ShellView.ButtonTextInfo, new RecordItemIndex(0));
            repo.ShellView.ButtonText.Click("54;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginView.PARTContentHost' at 17;6.", repo.LoginView.PARTContentHostInfo, new RecordItemIndex(1));
            repo.LoginView.PARTContentHost.Click("17;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'advanced{Return}' with focus on 'LoginView.TxtPassword'.", repo.LoginView.TxtPasswordInfo, new RecordItemIndex(2));
            repo.LoginView.TxtPassword.PressKeys("advanced{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShellView.FindAProductCtrlPlusS' at 94;8.", repo.ShellView.FindAProductCtrlPlusSInfo, new RecordItemIndex(3));
            repo.ShellView.FindAProductCtrlPlusS.Click("94;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad3}{NumPad0}{NumPad0}{NumPad0}{NumPad1}{Return}'.", new RecordItemIndex(5));
            Keyboard.Press("930001{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'QuickSearchView.Name' at 70;14.", repo.QuickSearchView.NameInfo, new RecordItemIndex(6));
            repo.QuickSearchView.Name.Click("70;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'QuickSearchView.PreOwned' at 29;9.", repo.QuickSearchView.PreOwnedInfo, new RecordItemIndex(7));
            repo.QuickSearchView.PreOwned.Click("29;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShellView.ButtonContent1' at 52;4.", repo.ShellView.ButtonContent1Info, new RecordItemIndex(8));
            repo.ShellView.ButtonContent1.Click("52;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShellView.ButtonContent' at 92;6.", repo.ShellView.ButtonContentInfo, new RecordItemIndex(9));
            repo.ShellView.ButtonContent.Click("92;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindCustomerView.PARTContentHost' at 117;8.", repo.FindCustomerView.PARTContentHostInfo, new RecordItemIndex(10));
            repo.FindCustomerView.PARTContentHost.Click("117;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(14));
            Keyboard.Press("8177221112{Return}");
            Delay.Milliseconds(1000);
            
            while(!repo.FindCustomerView.ListBoxItem.Enabled)
            { Delay.Milliseconds(100);  }          
            
            
            repo.FindCustomerView.ListBoxItem.Click();
            Delay.Milliseconds(1000);        
            
            while(!repo.ShellView.NotInterestedCommand.Enabled)
            { Delay.Milliseconds(100);  }

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{F8}'.", new RecordItemIndex(15));
            Keyboard.Press("{F8}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{F12}'.", new RecordItemIndex(16));
            Keyboard.Press("{F12}");
            Delay.Milliseconds(0);
            
            while(!repo.ShellView.RequestCashSettlement.Enabled)
            { Delay.Milliseconds(100);  }            

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{F5}'.", new RecordItemIndex(17));
            repo.ShellView.RequestCashSettlement.Click();
            Delay.Milliseconds(1000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{Decimal}{NumPad0}{NumPad7}{Return}'.", new RecordItemIndex(18));
            Keyboard.Press("1.07{Return}");
            Delay.Milliseconds(0);
            
             while(!repo.LoginView.AnotherTransaction.Visible)
            { Delay.Milliseconds(100);  }            

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Escape}'.", new RecordItemIndex(19));
            Keyboard.Press("{Escape}");
            Delay.Milliseconds(0);
            
            
       }
            
            
        }

    }
}