///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace StandaloneRetechPayWirthCash
{
    /// <summary>
    /// The class representing the StandaloneRetechPayWirthCashRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.0")]
    [RepositoryFolder("6e2a6ced-6c5f-46db-99e2-93674127280b")]
    public partial class StandaloneRetechPayWirthCashRepository : RepoGenBaseFolder
    {
        static StandaloneRetechPayWirthCashRepository instance = new StandaloneRetechPayWirthCashRepository();
        StandaloneRetechPayWirthCashRepositoryFolders.ShellViewAppFolder _shellview;
        StandaloneRetechPayWirthCashRepositoryFolders.QuickSearchViewAppFolder _quicksearchview;
        StandaloneRetechPayWirthCashRepositoryFolders.LoginViewAppFolder _loginview;
        StandaloneRetechPayWirthCashRepositoryFolders.FindCustomerViewAppFolder _findcustomerview;

        /// <summary>
        /// Gets the singleton class instance representing the StandaloneRetechPayWirthCashRepository element repository.
        /// </summary>
        [RepositoryFolder("6e2a6ced-6c5f-46db-99e2-93674127280b")]
        public static StandaloneRetechPayWirthCashRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public StandaloneRetechPayWirthCashRepository() 
            : base("StandaloneRetechPayWirthCashRepository", "/", null, 0, false, "6e2a6ced-6c5f-46db-99e2-93674127280b", ".\\RepositoryImages\\StandaloneRetechPayWirthCashRepository6e2a6ced.rximgres")
        {
            _shellview = new StandaloneRetechPayWirthCashRepositoryFolders.ShellViewAppFolder(this);
            _quicksearchview = new StandaloneRetechPayWirthCashRepositoryFolders.QuickSearchViewAppFolder(this);
            _loginview = new StandaloneRetechPayWirthCashRepositoryFolders.LoginViewAppFolder(this);
            _findcustomerview = new StandaloneRetechPayWirthCashRepositoryFolders.FindCustomerViewAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6e2a6ced-6c5f-46db-99e2-93674127280b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ShellView folder.
        /// </summary>
        [RepositoryFolder("c024f808-5220-4c5f-af15-64377af97fb7")]
        public virtual StandaloneRetechPayWirthCashRepositoryFolders.ShellViewAppFolder ShellView
        {
            get { return _shellview; }
        }

        /// <summary>
        /// The QuickSearchView folder.
        /// </summary>
        [RepositoryFolder("6290ae0e-7566-4fbe-8d64-62cff206adf0")]
        public virtual StandaloneRetechPayWirthCashRepositoryFolders.QuickSearchViewAppFolder QuickSearchView
        {
            get { return _quicksearchview; }
        }

        /// <summary>
        /// The LoginView folder.
        /// </summary>
        [RepositoryFolder("e0a9ed9c-2c6a-43b4-9889-b275380f3422")]
        public virtual StandaloneRetechPayWirthCashRepositoryFolders.LoginViewAppFolder LoginView
        {
            get { return _loginview; }
        }

        /// <summary>
        /// The FindCustomerView folder.
        /// </summary>
        [RepositoryFolder("eaf66e36-b247-4829-ae9f-681b3971dbc4")]
        public virtual StandaloneRetechPayWirthCashRepositoryFolders.FindCustomerViewAppFolder FindCustomerView
        {
            get { return _findcustomerview; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.0")]
    public partial class StandaloneRetechPayWirthCashRepositoryFolders
    {
        /// <summary>
        /// The ShellViewAppFolder folder.
        /// </summary>
        [RepositoryFolder("c024f808-5220-4c5f-af15-64377af97fb7")]
        public partial class ShellViewAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttontextInfo;
            RepoItemInfo _neworderInfo;
            RepoItemInfo _findaproductctrlplussInfo;
            RepoItemInfo _shortcutInfo;
            RepoItemInfo _buttoncontentInfo;
            RepoItemInfo _buttoncontent1Info;
            RepoItemInfo _buttoncontent2Info;
            RepoItemInfo _quicksearchlauncherviewmodellaunchsearcInfo;
            RepoItemInfo _notinterestedcommandInfo;
            RepoItemInfo _requestcashsettlementInfo;

            /// <summary>
            /// Creates a new ShellView  folder.
            /// </summary>
            public ShellViewAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ShellView", "/form[@automationid='ShellView']", parentFolder, 30000, null, true, "c024f808-5220-4c5f-af15-64377af97fb7", "")
            {
                _buttontextInfo = new RepoItemInfo(this, "ButtonText", "?/?/button[@automationid='NewOrder']/text[@automationid='ButtonText']", 30000, null, "40b9f416-a4e8-4585-b040-eb9aa3d3e8b5");
                _neworderInfo = new RepoItemInfo(this, "NewOrder", "?/?/button[@automationid='NewOrder']", 30000, null, "979e0594-10c9-44b1-afdf-df6a9005ba1b");
                _findaproductctrlplussInfo = new RepoItemInfo(this, "FindAProductCtrlPlusS", "?/?/button[@automationid='QuickSearchLauncherViewModel.LaunchSearch']/text[@name='Find a product   (Ctrl+S)']", 30000, null, "923aa877-876c-4584-bf31-8af52f754137");
                _shortcutInfo = new RepoItemInfo(this, "Shortcut", ".//list[@automationid='Items']/listitem[@classname='ListBoxItem' and @text~'^GameStop\\.POS\\.UI\\.ViewModel' and @orientation='None' and @iscontentelement='True' and @iscontrolelement='True' and @iskeyboardfocusable='True']/?/?/button[@automationid='ContinueButtonCommand']/text[@automationid='Shortcut']", 30000, null, "c4440f78-a458-4c41-8478-6cfa6a727037");
                _buttoncontentInfo = new RepoItemInfo(this, "ButtonContent", ".//list[@automationid='Items']/listitem[@classname='ListBoxItem' and @text~'^GameStop\\.POS\\.UI\\.ViewModel' and @orientation='None' and @iscontentelement='True' and @iscontrolelement='True' and @iskeyboardfocusable='True']/?/?/button[@automationid='FindCustomer']/text[@automationid='ButtonContent']", 30000, null, "0924c25b-cedf-4df6-8137-19c4d170ca25");
                _buttoncontent1Info = new RepoItemInfo(this, "ButtonContent1", ".//list[@automationid='Items']/listitem[@classname='ListBoxItem' and @text~'^GameStop\\.POS\\.UI\\.ViewModel' and @orientation='None' and @iscontentelement='True' and @iscontrolelement='True' and @iskeyboardfocusable='True']/?/?/button[@automationid='ContinueButtonCommand']/text[@automationid='ButtonContent']", 30000, null, "495fd7d8-3c29-4970-ba86-b0c92fa2963e");
                _buttoncontent2Info = new RepoItemInfo(this, "ButtonContent2", ".//list[@automationid='Items']/listitem[@classname='ListBoxItem' and @text~'^GameStop\\.POS\\.UI\\.ViewModel' and @orientation='None' and @iscontentelement='True' and @iscontrolelement='True' and @iskeyboardfocusable='True']/?/?/button[@automationid='NotInterestedCommand']/text[@automationid='ButtonContent']", 30000, null, "10b4cc19-1785-4ec7-8f86-db5ff1811279");
                _quicksearchlauncherviewmodellaunchsearcInfo = new RepoItemInfo(this, "QuickSearchLauncherViewModelLaunchSearc", "?/?/button[@automationid='QuickSearchLauncherViewModel.LaunchSearch']", 30000, null, "aab6d0d0-871b-40e0-9fda-28fcd0cd5e27");
                _notinterestedcommandInfo = new RepoItemInfo(this, "NotInterestedCommand", ".//list[@automationid='Items']/listitem[@classname='ListBoxItem' and @text~'^GameStop\\.POS\\.UI\\.ViewModel' and @orientation='None' and @iscontentelement='True' and @iscontrolelement='True' and @iskeyboardfocusable='True']/?/?/button[@automationid='NotInterestedCommand']", 30000, null, "eb3a1b1d-2689-4646-ad63-9eee7c4ca8b0");
                _requestcashsettlementInfo = new RepoItemInfo(this, "RequestCashSettlement", "?/?/element[@automationid='PaymentView']/button[@automationid='RequestCashSettlement']", 30000, null, "1e578b55-c852-4612-b3bf-a6dc3f412d42");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c024f808-5220-4c5f-af15-64377af97fb7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c024f808-5220-4c5f-af15-64377af97fb7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonText item.
            /// </summary>
            [RepositoryItem("40b9f416-a4e8-4585-b040-eb9aa3d3e8b5")]
            public virtual Ranorex.Text ButtonText
            {
                get
                {
                    return _buttontextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ButtonText item info.
            /// </summary>
            [RepositoryItemInfo("40b9f416-a4e8-4585-b040-eb9aa3d3e8b5")]
            public virtual RepoItemInfo ButtonTextInfo
            {
                get
                {
                    return _buttontextInfo;
                }
            }

            /// <summary>
            /// The NewOrder item.
            /// </summary>
            [RepositoryItem("979e0594-10c9-44b1-afdf-df6a9005ba1b")]
            public virtual Ranorex.Button NewOrder
            {
                get
                {
                    return _neworderInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NewOrder item info.
            /// </summary>
            [RepositoryItemInfo("979e0594-10c9-44b1-afdf-df6a9005ba1b")]
            public virtual RepoItemInfo NewOrderInfo
            {
                get
                {
                    return _neworderInfo;
                }
            }

            /// <summary>
            /// The FindAProductCtrlPlusS item.
            /// </summary>
            [RepositoryItem("923aa877-876c-4584-bf31-8af52f754137")]
            public virtual Ranorex.Text FindAProductCtrlPlusS
            {
                get
                {
                    return _findaproductctrlplussInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FindAProductCtrlPlusS item info.
            /// </summary>
            [RepositoryItemInfo("923aa877-876c-4584-bf31-8af52f754137")]
            public virtual RepoItemInfo FindAProductCtrlPlusSInfo
            {
                get
                {
                    return _findaproductctrlplussInfo;
                }
            }

            /// <summary>
            /// The Shortcut item.
            /// </summary>
            [RepositoryItem("c4440f78-a458-4c41-8478-6cfa6a727037")]
            public virtual Ranorex.Text Shortcut
            {
                get
                {
                    return _shortcutInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Shortcut item info.
            /// </summary>
            [RepositoryItemInfo("c4440f78-a458-4c41-8478-6cfa6a727037")]
            public virtual RepoItemInfo ShortcutInfo
            {
                get
                {
                    return _shortcutInfo;
                }
            }

            /// <summary>
            /// The ButtonContent item.
            /// </summary>
            [RepositoryItem("0924c25b-cedf-4df6-8137-19c4d170ca25")]
            public virtual Ranorex.Text ButtonContent
            {
                get
                {
                    return _buttoncontentInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ButtonContent item info.
            /// </summary>
            [RepositoryItemInfo("0924c25b-cedf-4df6-8137-19c4d170ca25")]
            public virtual RepoItemInfo ButtonContentInfo
            {
                get
                {
                    return _buttoncontentInfo;
                }
            }

            /// <summary>
            /// The ButtonContent1 item.
            /// </summary>
            [RepositoryItem("495fd7d8-3c29-4970-ba86-b0c92fa2963e")]
            public virtual Ranorex.Text ButtonContent1
            {
                get
                {
                    return _buttoncontent1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ButtonContent1 item info.
            /// </summary>
            [RepositoryItemInfo("495fd7d8-3c29-4970-ba86-b0c92fa2963e")]
            public virtual RepoItemInfo ButtonContent1Info
            {
                get
                {
                    return _buttoncontent1Info;
                }
            }

            /// <summary>
            /// The ButtonContent2 item.
            /// </summary>
            [RepositoryItem("10b4cc19-1785-4ec7-8f86-db5ff1811279")]
            public virtual Ranorex.Text ButtonContent2
            {
                get
                {
                    return _buttoncontent2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ButtonContent2 item info.
            /// </summary>
            [RepositoryItemInfo("10b4cc19-1785-4ec7-8f86-db5ff1811279")]
            public virtual RepoItemInfo ButtonContent2Info
            {
                get
                {
                    return _buttoncontent2Info;
                }
            }

            /// <summary>
            /// The QuickSearchLauncherViewModelLaunchSearc item.
            /// </summary>
            [RepositoryItem("aab6d0d0-871b-40e0-9fda-28fcd0cd5e27")]
            public virtual Ranorex.Button QuickSearchLauncherViewModelLaunchSearc
            {
                get
                {
                    return _quicksearchlauncherviewmodellaunchsearcInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The QuickSearchLauncherViewModelLaunchSearc item info.
            /// </summary>
            [RepositoryItemInfo("aab6d0d0-871b-40e0-9fda-28fcd0cd5e27")]
            public virtual RepoItemInfo QuickSearchLauncherViewModelLaunchSearcInfo
            {
                get
                {
                    return _quicksearchlauncherviewmodellaunchsearcInfo;
                }
            }

            /// <summary>
            /// The NotInterestedCommand item.
            /// </summary>
            [RepositoryItem("eb3a1b1d-2689-4646-ad63-9eee7c4ca8b0")]
            public virtual Ranorex.Button NotInterestedCommand
            {
                get
                {
                    return _notinterestedcommandInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NotInterestedCommand item info.
            /// </summary>
            [RepositoryItemInfo("eb3a1b1d-2689-4646-ad63-9eee7c4ca8b0")]
            public virtual RepoItemInfo NotInterestedCommandInfo
            {
                get
                {
                    return _notinterestedcommandInfo;
                }
            }

            /// <summary>
            /// The RequestCashSettlement item.
            /// </summary>
            [RepositoryItem("1e578b55-c852-4612-b3bf-a6dc3f412d42")]
            public virtual Ranorex.Button RequestCashSettlement
            {
                get
                {
                    return _requestcashsettlementInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RequestCashSettlement item info.
            /// </summary>
            [RepositoryItemInfo("1e578b55-c852-4612-b3bf-a6dc3f412d42")]
            public virtual RepoItemInfo RequestCashSettlementInfo
            {
                get
                {
                    return _requestcashsettlementInfo;
                }
            }
        }

        /// <summary>
        /// The QuickSearchViewAppFolder folder.
        /// </summary>
        [RepositoryFolder("6290ae0e-7566-4fbe-8d64-62cff206adf0")]
        public partial class QuickSearchViewAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nameInfo;
            RepoItemInfo _preownedInfo;
            RepoItemInfo _textdollar099Info;

            /// <summary>
            /// Creates a new QuickSearchView  folder.
            /// </summary>
            public QuickSearchViewAppFolder(RepoGenBaseFolder parentFolder) :
                    base("QuickSearchView", "/form[@automationid='QuickSearchView']", parentFolder, 30000, null, true, "6290ae0e-7566-4fbe-8d64-62cff206adf0", "")
            {
                _nameInfo = new RepoItemInfo(this, "Name", "?/?/list/listitem[1]/text[@automationid='Name']", 30000, null, "7aa8032b-dc1e-4b13-a125-35f85c05065f");
                _preownedInfo = new RepoItemInfo(this, "PreOwned", "?/?/button[@automationid='SelectPreOwnedSku' and @classname='Button' and @orientation='None' and @iscontentelement='True' and @iscontrolelement='True' and @iskeyboardfocusable='True']/text[@name='Pre-Owned']", 30000, null, "8eca2963-85e7-4872-aa02-a45668d7dec0");
                _textdollar099Info = new RepoItemInfo(this, "TextDollar099", "?/?/button[@automationid='SelectPreOwnedSku' and @classname='Button' and @orientation='None' and @iscontentelement='True' and @iscontrolelement='True' and @iskeyboardfocusable='True']/text[@name='$0.99']", 30000, null, "96e3afe1-aa5c-4dff-9715-a7dbf44b9769");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6290ae0e-7566-4fbe-8d64-62cff206adf0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6290ae0e-7566-4fbe-8d64-62cff206adf0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("7aa8032b-dc1e-4b13-a125-35f85c05065f")]
            public virtual Ranorex.Text Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("7aa8032b-dc1e-4b13-a125-35f85c05065f")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The PreOwned item.
            /// </summary>
            [RepositoryItem("8eca2963-85e7-4872-aa02-a45668d7dec0")]
            public virtual Ranorex.Text PreOwned
            {
                get
                {
                    return _preownedInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PreOwned item info.
            /// </summary>
            [RepositoryItemInfo("8eca2963-85e7-4872-aa02-a45668d7dec0")]
            public virtual RepoItemInfo PreOwnedInfo
            {
                get
                {
                    return _preownedInfo;
                }
            }

            /// <summary>
            /// The TextDollar099 item.
            /// </summary>
            [RepositoryItem("96e3afe1-aa5c-4dff-9715-a7dbf44b9769")]
            public virtual Ranorex.Text TextDollar099
            {
                get
                {
                    return _textdollar099Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextDollar099 item info.
            /// </summary>
            [RepositoryItemInfo("96e3afe1-aa5c-4dff-9715-a7dbf44b9769")]
            public virtual RepoItemInfo TextDollar099Info
            {
                get
                {
                    return _textdollar099Info;
                }
            }
        }

        /// <summary>
        /// The LoginViewAppFolder folder.
        /// </summary>
        [RepositoryFolder("e0a9ed9c-2c6a-43b4-9889-b275380f3422")]
        public partial class LoginViewAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _partcontenthostInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _anothertransactionInfo;

            /// <summary>
            /// Creates a new LoginView  folder.
            /// </summary>
            public LoginViewAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginView", "/form[@automationid='LoginView']", parentFolder, 30000, null, true, "e0a9ed9c-2c6a-43b4-9889-b275380f3422", "")
            {
                _partcontenthostInfo = new RepoItemInfo(this, "PARTContentHost", "text[@automationid='txtPassword']/container[@automationid='PART_ContentHost']", 30000, null, "bd319a76-3b11-4d50-94e0-2dbbdbe4d0d3");
                _txtpasswordInfo = new RepoItemInfo(this, "TxtPassword", "text[@automationid='txtPassword']", 30000, null, "3dbdebf0-ae0b-42e2-890c-4e75a0933b88");
                _anothertransactionInfo = new RepoItemInfo(this, "AnotherTransaction", "?/?/text[@automationid='Title']", 30000, null, "3d245348-79c8-405f-a728-2ded091b7dec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e0a9ed9c-2c6a-43b4-9889-b275380f3422")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e0a9ed9c-2c6a-43b4-9889-b275380f3422")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTContentHost item.
            /// </summary>
            [RepositoryItem("bd319a76-3b11-4d50-94e0-2dbbdbe4d0d3")]
            public virtual Ranorex.Container PARTContentHost
            {
                get
                {
                    return _partcontenthostInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTContentHost item info.
            /// </summary>
            [RepositoryItemInfo("bd319a76-3b11-4d50-94e0-2dbbdbe4d0d3")]
            public virtual RepoItemInfo PARTContentHostInfo
            {
                get
                {
                    return _partcontenthostInfo;
                }
            }

            /// <summary>
            /// The TxtPassword item.
            /// </summary>
            [RepositoryItem("3dbdebf0-ae0b-42e2-890c-4e75a0933b88")]
            public virtual Ranorex.Text TxtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("3dbdebf0-ae0b-42e2-890c-4e75a0933b88")]
            public virtual RepoItemInfo TxtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The AnotherTransaction item.
            /// </summary>
            [RepositoryItem("3d245348-79c8-405f-a728-2ded091b7dec")]
            public virtual Ranorex.Text AnotherTransaction
            {
                get
                {
                    return _anothertransactionInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AnotherTransaction item info.
            /// </summary>
            [RepositoryItemInfo("3d245348-79c8-405f-a728-2ded091b7dec")]
            public virtual RepoItemInfo AnotherTransactionInfo
            {
                get
                {
                    return _anothertransactionInfo;
                }
            }
        }

        /// <summary>
        /// The FindCustomerViewAppFolder folder.
        /// </summary>
        [RepositoryFolder("eaf66e36-b247-4829-ae9f-681b3971dbc4")]
        public partial class FindCustomerViewAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailaddressInfo;
            RepoItemInfo _partcontenthostInfo;
            RepoItemInfo _customerlookuptxtInfo;
            RepoItemInfo _listboxitemInfo;

            /// <summary>
            /// Creates a new FindCustomerView  folder.
            /// </summary>
            public FindCustomerViewAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FindCustomerView", "/form[@automationid='FindCustomerView']", parentFolder, 30000, null, true, "eaf66e36-b247-4829-ae9f-681b3971dbc4", "")
            {
                _emailaddressInfo = new RepoItemInfo(this, "EmailAddress", "?/?/list/listitem[2]/text[@automationid='EmailAddress']", 30000, null, "bc73a9d9-4e98-4ff9-8b17-c0f47083a915");
                _partcontenthostInfo = new RepoItemInfo(this, "PARTContentHost", "?/?/container[@automationid='PART_ContentHost']", 30000, null, "60acb003-2558-4f02-816f-3bd39400e79d");
                _customerlookuptxtInfo = new RepoItemInfo(this, "CustomerLookupTxt", "text[@automationid='CustomerLookupTxt']", 30000, null, "bad78379-c908-4b30-b4e8-d5fab1313c04");
                _listboxitemInfo = new RepoItemInfo(this, "ListBoxItem", "?/?/list[@automationid='CustomerSearchResult.CustomerSearchResults']/listitem[1]", 30000, null, "01f49b67-36d8-4963-af8c-47a8460745ca");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eaf66e36-b247-4829-ae9f-681b3971dbc4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eaf66e36-b247-4829-ae9f-681b3971dbc4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EmailAddress item.
            /// </summary>
            [RepositoryItem("bc73a9d9-4e98-4ff9-8b17-c0f47083a915")]
            public virtual Ranorex.Text EmailAddress
            {
                get
                {
                    return _emailaddressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EmailAddress item info.
            /// </summary>
            [RepositoryItemInfo("bc73a9d9-4e98-4ff9-8b17-c0f47083a915")]
            public virtual RepoItemInfo EmailAddressInfo
            {
                get
                {
                    return _emailaddressInfo;
                }
            }

            /// <summary>
            /// The PARTContentHost item.
            /// </summary>
            [RepositoryItem("60acb003-2558-4f02-816f-3bd39400e79d")]
            public virtual Ranorex.Container PARTContentHost
            {
                get
                {
                    return _partcontenthostInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTContentHost item info.
            /// </summary>
            [RepositoryItemInfo("60acb003-2558-4f02-816f-3bd39400e79d")]
            public virtual RepoItemInfo PARTContentHostInfo
            {
                get
                {
                    return _partcontenthostInfo;
                }
            }

            /// <summary>
            /// The CustomerLookupTxt item.
            /// </summary>
            [RepositoryItem("bad78379-c908-4b30-b4e8-d5fab1313c04")]
            public virtual Ranorex.Text CustomerLookupTxt
            {
                get
                {
                    return _customerlookuptxtInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CustomerLookupTxt item info.
            /// </summary>
            [RepositoryItemInfo("bad78379-c908-4b30-b4e8-d5fab1313c04")]
            public virtual RepoItemInfo CustomerLookupTxtInfo
            {
                get
                {
                    return _customerlookuptxtInfo;
                }
            }

            /// <summary>
            /// The ListBoxItem item.
            /// </summary>
            [RepositoryItem("01f49b67-36d8-4963-af8c-47a8460745ca")]
            public virtual Ranorex.ListItem ListBoxItem
            {
                get
                {
                    return _listboxitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListBoxItem item info.
            /// </summary>
            [RepositoryItemInfo("01f49b67-36d8-4963-af8c-47a8460745ca")]
            public virtual RepoItemInfo ListBoxItemInfo
            {
                get
                {
                    return _listboxitemInfo;
                }
            }
        }

    }
}