///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GamestopAutomation
{
    /// <summary>
    /// The class representing the GamestopAutomationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "4.1.4")]
    [RepositoryFolder("56b11c21-1377-43f1-b7a4-a953275544f8")]
    public partial class GamestopAutomationRepository : RepoGenBaseFolder
    {
        static GamestopAutomationRepository instance = new GamestopAutomationRepository();

        /// <summary>
        /// Gets the singleton class instance representing the GamestopAutomationRepository element repository.
        /// </summary>
        [RepositoryFolder("56b11c21-1377-43f1-b7a4-a953275544f8")]
        public static GamestopAutomationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GamestopAutomationRepository() 
            : base("GamestopAutomationRepository", "/", null, 0, false, "56b11c21-1377-43f1-b7a4-a953275544f8", ".\\RepositoryImages\\GamestopAutomationRepository56b11c21.rximgres")
        {
        }

#region Variables

        string _lv2 = "";

        /// <summary>
        /// Gets or sets the value of variable lv2.
        /// </summary>
        [TestVariable("82585934-3a8d-49bd-bbd9-2453f4b225e7")]
        public string lv2
        {
            get { return _lv2; }
            set { _lv2 = value; }
        }

        string _id = "";

        /// <summary>
        /// Gets or sets the value of variable id.
        /// </summary>
        [TestVariable("f77e1514-8911-49f8-993b-54b1c88cee8a")]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("56b11c21-1377-43f1-b7a4-a953275544f8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "4.1.4")]
    public partial class GamestopAutomationRepositoryFolders
    {
    }
}