///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Speech.AudioFormat;
using System.Speech.Synthesis;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

using System.Windows.Forms;



namespace Alpha
{
    public partial class APlaceToTryCodeAfterInit
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        /// 
        
     
      
        
        
        
        private void Init()
        {
            // Your recording specific initialization code goes here.
            
            
            //////////////////////////////////////////////////////////////////////////////////

            // PUT ANY CODE YOU WANT TO TEST HERE IT EXECUTES BEFORE ANY OTHER CODE
           

          
            
			Global.LogFileIndentLevel = 0;            
            
RanorexRepository repo = new RanorexRepository();


        	
        	string strMinute = System.DateTime.Now.Minute.ToString();
        	int intMinute = System.DateTime.Now.Minute;
        	
        	

        	
        	
          
						
//						string strCmdText;
//						strCmdText = @"wmic /output:aa.txt path win32_perfformatteddata_perfproc_process get Name, Caption, PercentProcessorTime, IDProcess /format:list";
//						System.Diagnostics.Process.Start("cmd.exe",strCmdText);

	            
	            
	            
//        	Bitmap image = Imaging.CaptureDesktopImage(new Rectangle()); 
//        	image.Save("aTest.jpg", System.Drawing.Imaging.ImageFormat.Jpeg); 
	            


//Report.Screenshot();
	
			//Ranorex.Unknown element = null;   


			
	            

			

			
			

	            
	            
//int a = 1;    








			//int APlaceToBreakPoint = 1;

            //////////////////////////////////////////////////////////////////////////////////              
            
            
            
        }

    }
}